In [2]:
import torch

In [3]:
threshold = 0.5
#confidences = torch.rand(size=(5, )) # .view(64, 1)
confidences = torch.tensor([0.25, 0.6, 0.4, 0.7, 0.2])
q_table = torch.rand(size=(5, 3))
best_q = torch.argmax(q_table, dim=1)
strategy = 99

In [4]:
print(confidences[:3])
print(q_table[:3])
print(best_q[:3])

tensor([0.2500, 0.6000, 0.4000])
tensor([[0.0954, 0.2578, 0.9832],
        [0.4053, 0.3217, 0.9218],
        [0.0769, 0.8691, 0.6586]])
tensor([2, 2, 1])


In [8]:
print(f"confidences : {confidences}")
print(f"q best : {best_q}")
print(f"threshold : {threshold}")
print(f"strategy : {strategy}")
print(f"action : {torch.where(confidences.lt(threshold), strategy, best_q)}")

confidences : tensor([0.2500, 0.6000, 0.4000, 0.7000, 0.2000])
q best : tensor([2, 2, 1, 2, 2])
threshold : 0.5
strategy : 99
action : tensor([99,  2, 99,  2, 99])


In [13]:
c = confidences

In [19]:
t = torch.where(c<threshold, strategy, best_q)

In [20]:
t

tensor([0, 1, 2, 2, 1])

In [17]:
strategy

1

In [10]:
# mask condition to keep

tensor([0])

In [36]:
# c = True if confidence < threshold, else False
c = torch.lt(confidences, threshold).squeeze()

In [37]:
torch.tensor([[strategy]])

tensor([[0]])

In [38]:
best_q

tensor([0, 1, 1, 0, 0, 2, 0, 0, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 2, 1, 1, 1, 2,
        0, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 0, 2, 0, 0, 1,
        1, 0, 2, 2, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 1])

In [42]:
a = torch.where(c==True, x=c, y=strategy)

TypeError: where() received an invalid combination of arguments - got (Tensor, y=int, x=Tensor), but expected one of:
 * (Tensor condition)
 * (Tensor condition, Tensor input, Tensor other)
      didn't match because some of the keywords were incorrect: y, x
 * (Tensor condition, Number self, Tensor other)
      didn't match because some of the keywords were incorrect: y, x
 * (Tensor condition, Tensor input, Number other)
      didn't match because some of the keywords were incorrect: y, x
 * (Tensor condition, Number self, Number other)
      didn't match because some of the keywords were incorrect: y, x


In [43]:
t = torch.nonzero(c)

In [44]:
t

tensor([[ 0],
        [ 3],
        [ 6],
        [ 8],
        [12],
        [13],
        [16],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [30],
        [31],
        [32],
        [33],
        [34],
        [35],
        [37],
        [38],
        [41],
        [42],
        [44],
        [51],
        [52],
        [53],
        [56],
        [59],
        [60],
        [61]])

In [40]:
c

tensor([ True, False, False,  True, False, False,  True, False,  True, False,
        False, False,  True,  True, False, False,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False, False, False,
         True,  True,  True,  True,  True,  True, False,  True,  True, False,
        False,  True,  True, False,  True, False, False, False, False, False,
        False,  True,  True,  True, False, False,  True, False, False,  True,
         True,  True, False, False])

In [35]:
a = torch.where(condition=torch.lt(confidences, threshold).squeeze(), x=torch.tensor([strategy]), y=best_q)

TypeError: where() received an invalid combination of arguments - got (y=Tensor, x=Tensor, condition=Tensor, ), but expected one of:
 * (Tensor condition)
 * (Tensor condition, Tensor input, Tensor other)
      didn't match because some of the keywords were incorrect: y, x
 * (Tensor condition, Number self, Tensor other)
      didn't match because some of the keywords were incorrect: y, x
 * (Tensor condition, Tensor input, Number other)
      didn't match because some of the keywords were incorrect: y, x
 * (Tensor condition, Number self, Number other)
      didn't match because some of the keywords were incorrect: y, x


In [14]:
c.size()

torch.Size([64, 1])

In [11]:
actions = torch.where(condition=confidences<threshold, x=q_table, y=torch.tensor([strategy]))

TypeError: where() received an invalid combination of arguments - got (y=Tensor, x=Tensor, condition=Tensor, ), but expected one of:
 * (Tensor condition)
 * (Tensor condition, Tensor input, Tensor other)
      didn't match because some of the keywords were incorrect: y, x
 * (Tensor condition, Number self, Tensor other)
      didn't match because some of the keywords were incorrect: y, x
 * (Tensor condition, Tensor input, Number other)
      didn't match because some of the keywords were incorrect: y, x
 * (Tensor condition, Number self, Number other)
      didn't match because some of the keywords were incorrect: y, x


In [25]:
d = torch.cat((confidences, q_table), dim=1)
d[:3]

tensor([[0.5888, 0.2606, 0.5103, 0.0944],
        [0.9398, 0.1994, 0.2125, 0.7854],
        [0.9027, 0.0709, 0.5118, 0.2473]])

In [27]:
data = d[:3]

In [29]:
def foo(row, strategy, thrsh):
    return strategy if row[0] < thresh else torch.argmax(row[1:])

In [ ]:
if strategy is not None:
    actions = torch.where(condition=confidences<threshold, x=torch.tensor([strategy]), y=best_q)

In [ ]:
if strategy is not None:
    actions = [strategy if c < threshold else torch.argmax(qvals) for c, qvals in zip(confidences, q_table)]
else:
    # get argmax for each item in batch
    actions = torch.argmax(q_table, dim=1)

In [30]:
strategy = 0
thresh = 0.25

In [31]:
d2 = [strategy if ]

AttributeError: module 'torch' has no attribute 'vmap'